stages:
  - setup
  - build
  - execute
  - test
  - deploy

variables:
  PACKAGE_NAME: TopNtupleAnalysis
  GIT_SSL_NO_VERIFY: "true"

.global: &global
  only:
    refs:
      - master

build_image:
  stage: deploy
  script:
    - ignore
  variables:
    FROM: gitlab-registry.cern.ch/atlas-phys/exot/hqt/r21-ttbar-1lep/hqtttresonancestools
    CONTEXT_DIR: /
    BUILD_ARG_1: CI_JOB_TOKEN=${CI_JOB_TOKEN}
  tags:
    - docker-image-build
  <<: *global

include:
  - project: 'ttreshad/hook'
    file: 'Hook.gitlab-ci.yml'

deploy-ttresfullhad:
  stage: deploy
  variables: 
    TO_PROJECT: ttResFullHad
    TO_PROJECT_URL: https://:@gitlab.cern.ch:8443/atlas-phys/exot/hqt/tt_tb_Resonances_Run2/ttResFullHad.git
    TO_BRANCH: canary
  extends: .deploy
  allow_failure: true
  <<: *global
